project:
  type: website

website:
  page-navigation: true
  title: "contabiliDados"
  site-url: "https://contabilidados.com.br/cntdd/"
  google-analytics: "G-2J79YYG9CZ"
  page-footer:
    left: "Blog made with [Quarto](https://quarto.org/), by cntdd Team. License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/)."
    right:
      - icon: youtube
        href: https://github.com/beatrizmilz/
      - icon: instagram
        href: https://instagram.com/ederlvz
      - icon: envelope
        href: mailto:milz.bea@gmail.com
  twitter-card:
    creator: "@cntdd"
    card-style: summary_large_image
  navbar:
    right:
      - text: Equipe
        menu:
          - text: Professores
            href: team/profs.qmd
          - text: Alunos
            href: team/alunos.qmd
      - text: Posts
        href: posts.qmd
      - text: cntdd
        href: cntdd.qmd
      - text: Eventos
        href: eventos/meetings.qmd
      - icon: instagram
        href: https://github.com/contabilidados
      - icon: youtube
        href: https://twitter.com/BeaMilz
      - icon: github
        href: https://twitter.com/BeaMilz

format:
  html:
    smooth-scroll: true
    theme: journal
    css: styles.css
    link-external-icon: false
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/www\.beamilz\.com\/**'
    citations-hover: true
    footnotes-hover: true
    include-in-header: meta.html
    toc: true
    code-link: true

editor: visual

comments:
  giscus:
    repo: beatrizmilz/blog-en
