project:
  type: website

website:
  favicon: icon.png
  page-navigation: true
  back-to-top-navigation: true
  title: "contabiliDados"
  site-url: "https://contabilidados.com.br/cntdd/"
  page-footer:
    left: "contabiliDados usou [Quarto](https://quarto.org/), basedo em [BeaMilz](https://beamilz.com/). License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/)."
    right:
      - icon: youtube
        href: https://www.youtube.com/watch?v=Bckx1xIqGto&list=PL2Kz0fa0V_r3ghh1iHWl31CYr5bVc0Jfo
      - icon: instagram
        href: https://www.instagram.com/contabilidados
      - icon: envelope
        href: mailto:contabilidados@ufersa.edu.br
  twitter-card:
    creator: "@cntdd"
    card-style: summary_large_image
  navbar:
    right:
      - text: Dash Indicadores
        href: https://kleberformiga.shinyapps.io/dashCVMaulas/
        target: _blank
      - text: Dash Mercado
        href: https://gecomt.shinyapps.io/dashboard/
        target: _blank
      - text: cntdd
        href: cntdd.qmd
      - text: Posts
        href: posts.qmd
      - text: Eventos
        href: meetings.qmd
      - text: Equipe
        href: membros.qmd
      - icon: instagram
        href: https://www.instagram.com/contabilidados
      - icon: youtube
        href: https://www.youtube.com/watch?v=Bckx1xIqGto&list=PL2Kz0fa0V_r3ghh1iHWl31CYr5bVc0Jfo
      - icon: github
        href: https://github.com/contabilidados
format:
  html:
    smooth-scroll: true
    theme:
      light: [sandstone, styles.css]
      dark: [cyborg, dark.css]
    link-external-icon: false
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/www\.contabilidados\.com.br\/**'
    citations-hover: true
    footnotes-hover: true
    toc: true
    code-link: true

lang: pt

editor: source

comments:
  giscus:
    repo: contabilidados/blog
